---
title: "E coli Genome Analysis"
author: "kat"
date: "October 12, 2015"
output: html_document
---
Here I'm working with data from software carpentry: http://rpubs.com/marschmi/117051


```{r set seed, echo=TRUE, eval=TRUE}
set.seed(79211104)
```

Below I am importing the **E coli data** from our data folder.

```{r Import Data, echo=TRUE, eval=TRUE}
metadata <- read.csv('data/Ecoli_metadata.csv') #load data from the data directory into an object named metadata
View(metadata) #looking at table within R studio
str(metadata) #shows the structure of an R object here, metadata
?str #get help with str
??str #all help pages with str in it
mean(metadata$genome_size) #calculating the mean of the genome size
```

Loading in a package through code chunk
```{r load packages, eval=TRUE}
#install.packages("ggplot2") #installing ggplot2 package
library("ggplot2") #loading and attaching packages
```

```{r data exploration, echo=TRUE, eval=TRUE, fig.center=TRUE}
##  Plot 1:  Let's look at the distribution of the genome size
ggplot(metadata, aes(x = genome_size)) +
  geom_bar(stat = "bin", binwidth=0.01) # create a bar plot (histogram) with bins by a genome size of 0.01


```

Making session info to make reproducible documents
```{r session info}
#library(devtools)
devtools::session_info() 
```





